#!/usr/bin/env python3
"""
Regenerate scientific_tools_consolidated/CODES_MISSING_PAPERS.md from the
current master list state. Lists every code that still has a PLACEHOLDER
paper line or no paper line at all, grouped by category.

Output is consumed by humans + downstream paper-fetching scripts.
"""
import re
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "scientific_tools_consolidated" / "MASTER_LIST_COMPLETE_372.md"
OUT = ROOT / "scientific_tools_consolidated" / "CODES_MISSING_PAPERS.md"

ENTRY_RE = re.compile(r'^\*\*([0-9]+[a-z]?)\.\s+(.+?)\*\*\*?(?:\s*\(.*?\))?\s*$')
CAT_RE = re.compile(r'^##\s+CATEGORY\s+(\d+):\s*(.+?)\s*\(\d+ tools\)\s*$', re.IGNORECASE)
SUB_RE = re.compile(r'^###\s+(\d+\.\d+)\s+(.+?)\s*\(\d+ tools\)\s*$')
LINK_RE = re.compile(r'^- Link:\s*\[([^\]]+)\]\(([^)]+)\)')
RES_RE = re.compile(r'^- Resources:\s*(.+?)\s*$')
PAPER_RE = re.compile(r'^- Paper:\s*(.*)$')


def parse(text):
    cat_id = cat_name = sub_id = sub_name = ''
    entries = []
    cur = None
    def _close():
        nonlocal cur
        if cur is not None:
            # Skip removed/superseded placeholders so total matches build script (847)
            if not cur['name'].startswith('[REMOVED'):
                entries.append(cur)
            cur = None
    for line in text.splitlines():
        m = CAT_RE.match(line)
        if m:
            cat_id, cat_name = m.group(1), m.group(2).strip()
            _close()
            continue
        m = SUB_RE.match(line)
        if m:
            sub_id, sub_name = m.group(1), m.group(2).strip()
            _close()
            continue
        m = ENTRY_RE.match(line)
        if m:
            _close()
            cur = {
                'idx': m.group(1), 'name': m.group(2).strip(),
                'cat_id': cat_id, 'cat': cat_name,
                'sub_id': sub_id, 'sub': sub_name,
                'paper_line': None, 'official': '', 'md_link': '',
            }
            continue
        if cur is None:
            continue
        if line.startswith('---'):
            _close()
            continue
        m = PAPER_RE.match(line)
        if m and cur['paper_line'] is None:
            cur['paper_line'] = line
            continue
        m = RES_RE.match(line)
        if m:
            cur['official'] = m.group(1)
            continue
        m = LINK_RE.match(line)
        if m:
            cur['md_link'] = m.group(2)
    _close()
    return entries


def is_missing(e):
    pl = e['paper_line']
    if pl is None:
        return True, 'no Paper line'
    if 'PLACEHOLDER' in pl:
        return True, 'PLACEHOLDER'
    # No .pdf link in line
    if '.pdf' not in pl:
        return True, 'no PDF link'
    return False, ''


def main():
    entries = parse(MASTER.read_text())
    total = len(entries)

    missing = []
    have = []
    for e in entries:
        miss, reason = is_missing(e)
        if miss:
            e['_reason'] = reason
            missing.append(e)
        else:
            have.append(e)

    by_cat = defaultdict(list)
    for e in missing:
        by_cat[(e['cat_id'], e['cat'])].append(e)

    out = []
    out.append('# Codes Still Missing Paper PDFs')
    out.append('')
    out.append(f'Auto-generated by `scripts/regen_missing_papers.py` from `MASTER_LIST_COMPLETE_372.md`.')
    out.append('')
    out.append('## Summary')
    out.append('')
    out.append(f'- **Total codes in database**: {total}')
    out.append(f'- **Codes with paper PDFs**: {len(have)} ({len(have)*100//total}%)')
    out.append(f'- **Codes still missing**:    {len(missing)} ({len(missing)*100//total}%)')
    out.append('')
    out.append('## Per-category status')
    out.append('')
    out.append('| Cat | Name | Total | Missing | Have | Coverage |')
    out.append('|-----|------|------:|--------:|-----:|---------:|')
    cat_totals = defaultdict(int)
    for e in entries:
        cat_totals[(e['cat_id'], e['cat'])] += 1
    for (cid, cname), tot in sorted(cat_totals.items(), key=lambda x: int(x[0][0] or 0) if x[0][0].isdigit() else 999):
        miss_n = len(by_cat.get((cid, cname), []))
        have_n = tot - miss_n
        pct = (have_n * 100 // tot) if tot else 0
        out.append(f'| {cid} | {cname} | {tot} | {miss_n} | {have_n} | {pct}% |')
    out.append('')
    out.append('## Codes still missing PDFs (by category)')
    out.append('')
    for (cid, cname), items in sorted(by_cat.items(), key=lambda x: int(x[0][0] or 0) if x[0][0].isdigit() else 999):
        out.append(f'### Category {cid}: {cname} ({len(items)} missing)')
        out.append('')
        out.append('| # | Code | Subcategory | Reason | Official URL |')
        out.append('|---|------|-------------|--------|--------------|')
        for e in items:
            url = e['official'] or '-'
            sub = f"{e['sub_id']} {e['sub']}".strip() or '-'
            out.append(f'| {e["idx"]} | {e["name"]} | {sub} | {e["_reason"]} | {url} |')
        out.append('')

    OUT.write_text('\n'.join(out) + '\n')
    print(f'Wrote {OUT} ({OUT.stat().st_size} bytes)')
    print(f'Total: {total}  Have: {len(have)}  Missing: {len(missing)}')


if __name__ == '__main__':
    main()
